package dev.iainkirkham.mental_planner_backend.pomodoro;

import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;

@Entity
@Table(name = "pomodoro_session")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class PomodoroSession {
    /**
     * This is the unique identifier of the pomodoro session, it is both the primary key and is auto-generated by the database
     * on insertion of a new entry.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The date and time of when the mood entry was recorded.
     * The time is provided in UTC.
     */
    @NotNull
    @Column(name = "start_time", nullable = false)
    private Instant startTime;

    /**
     * The date and time of when the mood entry was recorded.
     * The time is provided in UTC.
     */
    @Column(name = "end_time")
    private Instant endTime;

    @Min(0)
    @Column(nullable = false)
    private int duration;

    /**
     * The pomodoro session score from ranging from 1 (very bad) to 5 (very good)
     */
    @Min(1)
    @Max(5)
    @Column(name = "score")
    private Short score;

    /**
     * Optional notes about the mood entry.
     * Stored as text in the database to allow user to record long descriptions if required.
     */
    @Column(name = "notes", length = 1000)
    private String notes;
}