package dev.iainkirkham.mental_planner_backend.taskplanner;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * This entity represents a subtask within the mental planner application.
 */
@Entity
@Table(name = "sub_tasks")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SubTask {

    /**
     * This is the unique identifier of the subtask, it is both the primary key and is auto-generated by the database
     * on insertion of a new entry.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title or name of the subtask.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Indicates whether the user has completed this subtask.
     */
    private boolean completed = false;

    /**
     * Reference to the parent Task that this subtask belongs to.
     * This establishes a Many-to-One relationship where multiple subtasks can belong to a single task.
     * FetchType.LAZY means the task will be loaded only when accessed for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private Task task;
}
