ALTER TABLE task ADD COLUMN planned_minutes INTEGER;
ALTER TABLE task ADD COLUMN actual_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE task ADD COLUMN category VARCHAR(50);
ALTER TABLE task ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS subtask (
    id BIGSERIAL PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_subtask_task_id ON subtask(task_id);
