package dev.iainkirkham.mental_planner_backend.tasks;

import dev.iainkirkham.mental_planner_backend.security.EncryptedStringConverter;
import dev.iainkirkham.mental_planner_backend.timeentries.TaskTimeEntry;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;
import java.time.LocalDate;

@Entity
@Table(name = "task")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Task {
    /**
     * This is the unique identifier of the task, it is both the primary key and is auto-generated by the database
     * on insertion of a new entry.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Convert(converter = EncryptedStringConverter.class)
    @Column(nullable = false, columnDefinition = "TEXT")
    @ToString.Exclude
    private String title;

    @Convert(converter = EncryptedStringConverter.class)
    @Column(columnDefinition = "TEXT")
    @ToString.Exclude
    private String description;

    /**
     * The day this task belongs to, in the planner's backlog/timeline view.
     */
    @NotNull
    @Column(name = "scheduled_date", nullable = false)
    private LocalDate scheduledDate;

    /**
     * When the task is scheduled onto the timeline. Null means the task sits in the unscheduled backlog.
     * Provided in UTC.
     */
    @Column(name = "start_time")
    private Instant startTime;

    /**
     * Provided in UTC. Null means the task sits in the unscheduled backlog.
     */
    @Column(name = "end_time")
    private Instant endTime;

    @Column(nullable = false)
    private boolean completed = false;

    /**
     * Ordering of unscheduled tasks within the backlog list.
     */
    @Column(name = "sort_order", nullable = false)
    private int sortOrder = 0;

    /**
     * Estimated duration in minutes, shown as the card's planned-time pill and summed
     * into the day column's workload counter. Null means no estimate has been set.
     */
    @Column(name = "planned_minutes")
    private Integer plannedMinutes;

    /**
     * Minutes actually tracked against this task via start/pause time tracking.
     * Mutated only through {@link #applyManualEntry}, {@link #unwindManualEntry}, and
     * {@link #recordTimerCheckpoint} - see those for the rules governing this total.
     */
    @Setter(AccessLevel.NONE)
    @Column(name = "actual_minutes", nullable = false)
    private int actualMinutes = 0;

    /**
     * Free-form category/tag, rendered as a pill on the card (e.g. "product", "planning").
     */
    @Convert(converter = EncryptedStringConverter.class)
    @Column(columnDefinition = "TEXT")
    @ToString.Exclude
    private String category;

    /**
     * Archived tasks are excluded from the planner's day/week views but not deleted.
     */
    @Column(nullable = false)
    private boolean archived = false;

    /**
     * How urgently this task needs attention, shown as a colored marker on the card.
     * Never null - {@link #setPriority} defaults a null argument to {@code NORMAL}, since
     * priority is optional on the client's request DTO.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 10)
    private TaskPriority priority = TaskPriority.NORMAL;

    /**
     * The Clerk user ID of the user who created this task.
     * This field is used to ensure data isolation between users.
     */
    @Column(name = "user_id")
    private String userId;

    /**
     * Adds a manually-logged time entry's minutes onto the tracked total. Manual entries have
     * no other path to update the total, unlike stopwatch/countdown runs which are reflected
     * via {@link #recordTimerCheckpoint} instead.
     *
     * @param minutes the manual entry's minutes; must be positive.
     */
    public void applyManualEntry(int minutes) {
        this.actualMinutes += minutes;
    }

    /**
     * Unwinds a manually-logged time entry's minutes from the tracked total (clamped at 0),
     * used when that entry is deleted.
     *
     * @param minutes the deleted manual entry's minutes; must be positive.
     */
    public void unwindManualEntry(int minutes) {
        this.actualMinutes = Math.max(0, this.actualMinutes - minutes);
    }

    /**
     * Sets the tracked total to a stopwatch or countdown run's elapsed total, sent as a
     * checkpoint by the client during (or at the end of) that run. Recorded as history
     * separately, via a {@link TaskTimeEntry} with source {@code STOPWATCH} or
     * {@code COUNTDOWN}; those entries never touch this total directly.
     *
     * @param totalMinutes the run's elapsed total in minutes; must not be negative.
     */
    public void recordTimerCheckpoint(int totalMinutes) {
        this.actualMinutes = totalMinutes;
    }

    /**
     * Sets this task's priority, defaulting to {@code NORMAL} when given null - priority is
     * optional on the client's request DTO, but the column itself is non-nullable.
     */
    public void setPriority(TaskPriority priority) {
        this.priority = priority != null ? priority : TaskPriority.NORMAL;
    }
}
