package dev.iainkirkham.mental_planner_backend.tasks;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;
import java.time.LocalDate;

@Entity
@Table(name = "task")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Task {
    /**
     * This is the unique identifier of the task, it is both the primary key and is auto-generated by the database
     * on insertion of a new entry.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(nullable = false)
    private String title;

    @Column(length = 2000)
    private String description;

    /**
     * The day this task belongs to, in the planner's backlog/timeline view.
     */
    @NotNull
    @Column(name = "scheduled_date", nullable = false)
    private LocalDate scheduledDate;

    /**
     * When the task is scheduled onto the timeline. Null means the task sits in the unscheduled backlog.
     * Provided in UTC.
     */
    @Column(name = "start_time")
    private Instant startTime;

    /**
     * Provided in UTC. Null means the task sits in the unscheduled backlog.
     */
    @Column(name = "end_time")
    private Instant endTime;

    @Column(nullable = false)
    private boolean completed = false;

    /**
     * Ordering of unscheduled tasks within the backlog list.
     */
    @Column(name = "sort_order", nullable = false)
    private int sortOrder = 0;

    /**
     * Estimated duration in minutes, shown as the card's planned-time pill and summed
     * into the day column's workload counter. Null means no estimate has been set.
     */
    @Column(name = "planned_minutes")
    private Integer plannedMinutes;

    /**
     * Minutes actually tracked against this task via start/pause time tracking.
     */
    @Column(name = "actual_minutes", nullable = false)
    private int actualMinutes = 0;

    /**
     * Free-form category/tag, rendered as a pill on the card (e.g. "product", "planning").
     */
    @Column(length = 50)
    private String category;

    /**
     * Archived tasks are excluded from the planner's day/week views but not deleted.
     */
    @Column(nullable = false)
    private boolean archived = false;

    /**
     * How urgently this task needs attention, shown as a colored marker on the card.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 10)
    private TaskPriority priority = TaskPriority.NORMAL;

    /**
     * The Clerk user ID of the user who created this task.
     * This field is used to ensure data isolation between users.
     */
    @Column(name = "user_id")
    private String userId;
}
